#- name: Install werkzeug==0.16.0
#  sudo pip install --upgrade Flask
---

- name: Wait for updates / upgrades from user data script to release lock
  script: wait-for-apt-on-startup.sh

- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    upgrade: "yes" # Needs to be quoted
    force_apt_get: yes
    cache_valid_time: 86400 #One day

- name: Install required packages
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    state: latest
    update_cache: yes
  vars:
    packages:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - linux-aws
      - awscli
      - curl
      - jq
      - python3-pip
      - python-pip
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-dev

- name: Install pip packages
  pip:
    name: "{{ pippkgs }}"
    executable: pip
    state: present
  vars:
    pippkgs:
      - cryptography
      - werkzeug==0.16.1

- name: mount efs
  import_tasks: efs.yml
