version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: appsilon/ci-base:1.0
    steps:
      - checkout
      - run:
          command: |
            R -e "install.packages('testthat')"
      - run:
          command: |
            R -e "testthat::test_dir('tests')"
      - store_artifacts:
          path: man/
          destination: man


